apiVersion: v1
kind: Service
metadata:
  name: {{ include "geektime-ordering-api.fullname" . }}
  labels:
    {{- include "geektime-ordering-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
    - port: 81
      targetPort: http2
      protocol: TCP
      name: http2
    - port: 443
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "geektime-ordering-api.selectorLabels" . | nindent 4 }}
