{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "geektime-mobile-apiaggregator.serviceAccountName" . }}
  labels:
{{ include "geektime-mobile-apiaggregator.labels" . | nindent 4 }}
{{- end -}}
